services:
  postgres:
    image: postgres:16-alpine
    container_name: sicad_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: sicad_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - network

  backend-1:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sicad_backend-1
    restart: always
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5001:5000"
    networks:
      - network

  backend-2:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sicad_backend-2
    restart: always
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5002:5000"
    networks:
      - network

  nginx:
    image: nginx:alpine
    container_name: sicad_load-balancer
    restart: always
    depends_on:
      - backend-1
      - backend-2
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - network

  bore:
    image: ekzhang/bore:latest
    container_name: sicad_bore
    restart: always
    command: local 8080 --to bore.pub --local-host sicad_load-balancer
    depends_on:
      - nginx
    networks:
      - network

volumes:
  postgres_data:
  redis_data:

networks:
  network:
    driver: bridge
