services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sicad_network

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - sicad_network

  backend-1:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-1
    ports:
      - '5001:5000'
    depends_on:
      - postgres
      - redis
    restart: always
    networks:
      - sicad_network

  backend-2:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-2
    ports:
      - '5002:5000'
    depends_on:
      - postgres
      - redis
    restart: always
    networks:
      - sicad_network

  nginx:
    image: nginx:alpine
    ports:
      - "8080:8080"
    container_name: load-balancer
    depends_on:
      - backend-1
      - backend-2
    restart: always
    networks:
      - sicad_network


  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare_tunnel
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - nginx
    networks:
      - sicad_network

volumes:
  postgres_data:
  redis_data:

networks:
  sicad_network:
    driver: bridge