events {}

stream {
    upstream meus_servidores_socket {
        least_conn;
        server backend-1:5000;
        server backend-2:5000;
    }

    server {
        listen 8080;
        proxy_pass meus_servidores_socket;
        proxy_connect_timeout 5s;
        proxy_timeout 10m;
    }
}